"""Imports the models from the Clis project, generating their preview animation in the process.

Note that this script expects to be in Scripts/ folder of the Unity project.
It also exports the holds to ../Models/Holds/.
"""

import os
import argparse
import shutil
import hashlib
from subprocess import Popen
from yaml import load, dump
from yaml import CLoader as Loader, CDumper as Dumper

def get_file_hashsum(path, characters=12):
    """Return the hashsum of the file contents."""
    with open(path) as f:
        return hashlib.sha256(f.read().encode("utf-8")).hexdigest()[:12]


cwd = os.getcwd()

os.chdir(os.path.dirname(os.path.abspath(__file__)))

parser = argparse.ArgumentParser()

parser.add_argument(
    "path",
    help="The path to the models/ folder generated by Clis.",
)

arguments = parser.parse_args()

from_dir = os.path.join(cwd, arguments.path)
to_dir = os.path.join("..", "Models", "Holds")

if not os.path.exists(to_dir):
    os.makedirs(to_dir)

shutil.copy(os.path.join(from_dir, "holds.yaml"), os.path.join(to_dir, "holds.yaml"))

# read the YAML and copy the contents of the folders
with open(os.path.join(from_dir, "holds.yaml")) as f:
    data = load(f.read(), Loader=Loader)

for key in data:
    # find the folder with the key
    for file in os.listdir(from_dir):
        objfile = os.path.join(from_dir, file, "model.obj")

        if os.path.exists(objfile) and get_file_hashsum(objfile) == key:
            break

    hold_folder = os.path.join(from_dir, file)

    # copy over the model and its texture files
    for file in ["model.obj", "model.mtl", "model.jpg"]:
        _, ext = os.path.splitext(file)

        dest_file_stub = os.path.join(to_dir, key)
        dest_file = dest_file_stub + ext

        shutil.copy(os.path.join(hold_folder, file), dest_file)

        if ext == ".obj":
            # generate the preview for the hold
            Popen(["python3", "GenerateHoldPreviewVideo.py", dest_file, dest_file_stub + ".mp4"]).communicate()

        # replace the path to the texture in the mtl file so it's relative to Unity root
        if ext == ".mtl":
            with open(dest_file) as f:
                contents = f.read()

            contents = contents.replace(
                "model.jpg", os.path.join("Models", "Holds", key + ".jpg")
            )

            with open(dest_file, "w") as f:
                f.write(contents)

# TODO: warn about models that were not found
# TODO: only copy files that were not in already
# TODO: warn about models that were found but should not have been
